<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Athena</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
		
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="<?php echo BOOTSTRAP_CSS ?>">
        <link rel="stylesheet" href="<?php echo BOOTSTRAP_THEME_CSS ?>">
        <link rel="stylesheet" href="<?php echo BOOTSTRAP_RESPONSIVE_CSS ?>">
        <link rel="stylesheet" href="<?php echo ATHENA_CSS ?>">
        <link rel="stylesheet" href="<?php echo GLYPHICONS_CSS ?>">
        
        <link rel="stylesheet" href="css/main.css">
        <script src="<?php echo MODERNIZR ?>"></script>
        <script src="<?php echo JQUERY ?>"></script>
        <script src="<?php echo TCHAT ?>"></script>
<!--        <link href="css/custom-scrollbar-plugin/jquery.mCustomScrollbar.css" rel="stylesheet" type="text/css" /> -->
<!-- 		<script src="js/plugins/custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script> -->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index"><img title="Athena" src="<?php echo PUB_PATH . '/img/logo.png'?>" /></a>
        </div>
        <div class="navbar-collapse collapse">
        <?php if(empty($_SESSION['disauth']) || $_SESSION['disauth'] == false): ?>
        <?php else:?>
        	<a href="/index?disauth=disconnect">Se déconnecter</a>
        <?php endif;?>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
	
		<?php echo $page?>
	
    </div> <!-- /container -->
    <footer>
      <p>Athena - Projet RPID1 Ip-formation - 2013</p>
    </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.1.min.js"><\/script>')</script>

        <script src="js/vendor/bootstrap.min.js"></script>

        <script src="js/plugins.js"></script>
        <script src="js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src='//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
	