    <div class="container">
      <div class="row">
      <div class="col-lg-4">
      </div>
        <div class="col-lg-4">
          <h1>Bienvenue</h1>
          <p>Pour utiliser le tchat, Veuillez vous identifier.</p>
          <p><?php if(isset($_SESSION['message'])){echo $_SESSION['message'];}else{echo '';};?></p>
          <form action="" method="post">
            <div class="form-group">
              <input type="text" placeholder="Login" class="form-control" name="login">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Mot de passe" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-success" name="log">Se connecter</button>
          </form>
        </div>
      </div>