<div id="conteneur" style="width:94%; margin-bottom:200px;">
    <h1>Mon tchat, connectez en tant que <?php echo $_SESSION["pseudo"];?></h1>
    <div id="connected">
	
    </div>
  
  
  <div id="tchatForm" style="position:fixed;bottom:0;width:100%;">
       <form method="post" action="#">
	  <div style="margin-right:110px;">
	      <textarea name="message" style="width:100%;"></textarea>
	  </div>
	  <div style="position:absolute; top:12px; right:0;">
	      <input type="submit" value="Envoyer"/>
	  </div>
	</form>      
  </div>
